server:
  port: 9090

spring:
  application:
    name: IC-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id : INSURANCE-COMPANIES
          uri: lb://INSURANCE-COMPANIES
          predicates:
            - Path=/insurance/**
          filters:
            - AuthenticationFilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}