server:
  port: 9898

spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: root
      database: ic_api
      port: 27017
      host: ${DB_HOST:localhost}
  application:
    name: AUTH-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}